move CR6 SE Community to root

diff --git a/buildroot/bin/build_all_examples b/buildroot/bin/build_all_examples
--- a/buildroot/bin/build_all_examples
+++ b/buildroot/bin/build_all_examples
@@ -1,81 +1,62 @@
 #!/usr/bin/env bash
-#
-# build_all_examples base_branch [resume_point]
-#
 
-GITREPO=https://github.com/MarlinFirmware/Configurations.git
-STAT_FILE=./.pio/.buildall
+echo "This script will attempt to build Marlin for all known configurations."
+echo "In case of failure, the current configuration remains in your repository."
+echo "To revert to your current version, run 'git checkout -f'."
 
-# Check dependencies
-which curl 1>/dev/null 2>&1 || { echo "curl not found! Please install it."; exit ; }
-which git 1>/dev/null 2>&1 || { echo "git not found! Please install it."; exit ; }
-
-SED=$(command -v gsed 2>/dev/null || command -v sed 2>/dev/null)
-[[ -z "$SED" ]] && { echo "No sed found, please install sed" ; exit 1 ; }
-
-SELF=`basename "$0"`
+self=`basename "$0"`
 HERE=`dirname "$0"`
 
-# Check if called in the right location
-[[ -e "Marlin/src" ]] || { echo -e "This script must be called from a Marlin working copy with:\n ./buildroot/bin/$SELF $1" ; exit ; }
+# Check dependencies
+which curl 1>/dev/null 2>&1 || { echo "curl not found, please install it"; exit ; }
+which git 1>/dev/null 2>&1 || { echo "git not found, please install it"; exit ; }
+if [ -z "$1" ]; then
+  echo ""
+  echo "ERROR: "
+  echo "  Expected parameter: $self base_branch [resume_point]"
+  echo "  with:"
+  echo "         base_branch              The branch in the Configuration repository to use"
+  echo "         resume_point             If not empty, resume building from this board"
 
-if [[ $# -lt 1 || $# -gt 2 ]]; then
-  echo "Usage: $SELF base_branch [resume_point]
-  base_branch  - Configuration branch to download and build
-  resume_point - Configuration path to start from"
   exit
 fi
 
-echo "This script downloads all Configurations and builds Marlin with each one."
-echo "On failure the last-built configs will be left in your working copy."
-echo "Restore your configs with 'git checkout -f' or 'git reset --hard HEAD'."
-
-# If -c is given start from the last attempted build
-if [[ $1 == '-c' ]]; then
-  if [[ -f "$STAT_FILE" ]]; then
-    read BRANCH FIRST_CONF <"$STAT_FILE"
-  else
-    echo "Nothing to continue"
-    exit
-  fi
-else
-  BRANCH=${1:-"import-2.0.x"}
-  FIRST_CONF=$2
+# Check if called in the right folder
+if [ ! -e "Marlin/src" ]; then
+  echo "This script must be called from the root folder of a Marlin repository, please navigate to this folder and call:"
+  echo "buildroot/ci-check/$self $1"
+  exit
 fi
 
 # Check if the current repository has unmerged changes
-if [[ -z "$FIRST_CONF" ]]; then
-  git diff --quiet || { echo "The working copy is modified. Commit or stash changes before proceeding."; exit ; }
+if [ -z "$2" ]; then
+  git diff --quiet || { echo "Your current repository is not clean. Either commit your change or stash them, and re-run this script"; exit ; }
 else
-  echo "Resuming from $FIRST_CONF"
+  echo "Resuming from $2"
 fi
 
-# Create a temporary folder inside .pio
-TMP=./.pio/build-$BRANCH
-[[ -d "$TMP" ]] || mkdir -p $TMP
+TMPDIR=`mktemp -d`
 
-# Download Configurations into the temporary folder
-if [[ ! -e "$TMP/README.md" ]]; then
-  echo "Downloading Configurations from GitHub into $TMP"
-  git clone --depth=1 --single-branch --branch "$BRANCH" $GITREPO "$TMP" || { echo "Failed to clone the configuration repository"; exit ; }
-else
-  echo "Using previously downloaded Configurations at $TMP"
+# Ok, let's do our stuff now
+# First extract the current temporary folder
+echo "Fetching configuration repository"
+if [ ! -e "$TMPDIR/README.md" ]; then
+  git clone --single-branch --branch "$1" https://github.com/MarlinFirmware/Configurations.git "$TMPDIR" || { echo "Failed to clone the configuration repository"; exit ; }
+  rm -r $TMPDIR/.git
 fi
 
-echo -e "Start building now...\n====================="
+echo
+echo "Start building now..."
+echo "====================="
 shopt -s nullglob
-IFS='
-'
-CONF_TREE=$( ls -d "$TMP"/config/examples/*/ "$TMP"/config/examples/*/*/ "$TMP"/config/examples/*/*/*/ "$TMP"/config/examples/*/*/*/*/ | grep -vE ".+\.(\w+)$" )
-for CONF in $CONF_TREE ; do
-  DIR=$( echo $CONF | sed "s|$TMP/config/examples/||" )
-  [[ ! -z $FIRST_CONF ]] && [[ $FIRST_CONF != $DIR && "$FIRST_CONF/" != $DIR ]] && continue
-  unset FIRST_CONF
-  compgen -G "${CONF}Con*.h" > /dev/null || continue
-  echo -e "$BRANCH\n$DIR" >"$STAT_FILE"
-  "$HERE/build_example" "internal" "$TMP" "$DIR" || { echo "Failed to build $DIR"; exit ; }
+for config in $TMPDIR/config/examples/*/; do
+  [ -d "${config}" ] || continue
+  base=`basename "$config"`
+  if [ ! -z "$2" ] && [ "$2" != "$base" ]; then
+    echo "Skipping $base..."
+    continue
+  fi
+  "$HERE/build_example" "internal" "$TMPDIR" "$base" || { echo "Failed to build $base"; exit ; }
 done
 
-# Delete the temp folder and build state
-[[ -e "$TMP/config/examples" ]] && rm -rf "$TMP"
-rm "$STAT_FILE"
+rm -r "$TMPDIR"
